spring.application.name=feira-livre-nucleo
spring.datasource.url=jdbc:sqlite:./data/nucleo.db?transaction_mode=IMMEDIATE
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
server.port=8081
server.error.include-message=always
servicos.producao.url=${PRODUCAO_URL:http://localhost:8082}
servicos.entrega.url=${ENTREGA_URL:http://localhost:8083}
