PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS usuario (id INTEGER PRIMARY KEY, nome TEXT NOT NULL, email TEXT NOT NULL UNIQUE, senha TEXT NOT NULL DEFAULT '123456');
CREATE TABLE IF NOT EXISTS pedido (id INTEGER PRIMARY KEY, comprador_id INTEGER NOT NULL, status TEXT NOT NULL, valor_total REAL NOT NULL, data_pedido TEXT NOT NULL, FOREIGN KEY(comprador_id) REFERENCES usuario(id));
CREATE TABLE IF NOT EXISTS pedido_sequencia (id INTEGER PRIMARY KEY, valor INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS item_pedido (id INTEGER PRIMARY KEY AUTOINCREMENT, pedido_id INTEGER NOT NULL, produto_id INTEGER NOT NULL, produto_nome TEXT NOT NULL, vendedor_id INTEGER NOT NULL, quantidade INTEGER NOT NULL, preco_unitario REAL NOT NULL, subtotal REAL NOT NULL, FOREIGN KEY(pedido_id) REFERENCES pedido(id));
CREATE TABLE IF NOT EXISTS fatura (id INTEGER PRIMARY KEY AUTOINCREMENT, pedido_id INTEGER NOT NULL, valor REAL NOT NULL, status TEXT NOT NULL, FOREIGN KEY(pedido_id) REFERENCES pedido(id));
