spring.application.name=feira-livre-producao
spring.datasource.url=jdbc:sqlite:./data/producao.db?transaction_mode=IMMEDIATE
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
server.port=8082
server.error.include-message=always
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
