spring.application.name=feira-livre
spring.datasource.url=jdbc:sqlite:./data/feira-livre.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
server.port=8080
